# Generated by Django 6.0.5 on 2026-06-01 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Supplier name')),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+\\-\\s()]{6,20}$')])),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=30, verbose_name='GST / VAT number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gst_number', ''), _negated=True), fields=('name', 'gst_number'), name='unique_supplier_name_gst')],
            },
        ),
    ]
