# Generated by Django 6.0.5 on 2026-06-01 10:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_reserved_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='SWO number')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('wo_type', models.CharField(choices=[('assembly', 'Assembly (produce finished stock)'), ('service', 'Service / Repair (consume only)')], default='assembly', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released (materials reserved)'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('reserved', models.BooleanField(default=False)),
                ('produced_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Item to build (assembly) or service.', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.PositiveIntegerField(default=0)),
                ('consumed_quantity', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_lines', to='products.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.workorder')),
            ],
            options={
                'ordering': ['component__name'],
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Units of this component per 1 finished unit.', validators=[django.core.validators.MinValueValidator(1)])),
                ('component', models.ForeignKey(help_text='A raw material / part consumed to build it.', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='products.product')),
                ('product', models.ForeignKey(help_text='The finished product being built.', on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='products.product')),
            ],
            options={
                'ordering': ['component__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'component'), name='unique_component_per_bom'), models.CheckConstraint(condition=models.Q(('product', models.F('component')), _negated=True), name='bom_component_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', '-created_at'], name='production__status_4534c1_idx'),
        ),
    ]
