# Generated by Django 6.0.5 on 2026-06-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Inventory Manager'), ('staff', 'Staff'), ('auditor', 'Auditor')], db_index=True, default='staff', max_length=20),
        ),
    ]
