# Generated by Django 6.0.5 on 2026-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Inventory Manager'), ('staff', 'Staff'), ('auditor', 'Auditor'), ('planner', 'Production Planner'), ('supervisor', 'Floor Supervisor'), ('technician', 'Technician')], db_index=True, default='staff', max_length=20),
        ),
    ]
