# Generated by Django 6.0.5 on 2026-06-01 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjust', 'Stock Adjustment')], db_index=True, max_length=10)),
                ('quantity', models.IntegerField()),
                ('quantity_change', models.IntegerField(default=0, editable=False)),
                ('resulting_stock', models.IntegerField(default=0, editable=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.product')),
                ('source_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='purchases.purchaseorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_s_product_6d60d9_idx'), models.Index(fields=['transaction_type', '-created_at'], name='inventory_s_transac_85a8a5_idx')],
            },
        ),
    ]
