# Generated by Django 6.0.5 on 2026-06-01 07:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ca_name_693421_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('pcs', 'Piece'), ('box', 'Box'), ('kg', 'Kilogram'), ('g', 'Gram'), ('ltr', 'Litre'), ('m', 'Meter'), ('pack', 'Pack'), ('dozen', 'Dozen')], default='pcs', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'), models.Index(fields=['status'], name='products_pr_status_041708_idx'), models.Index(fields=['category', 'status'], name='products_pr_categor_75eeb5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='product_purchase_price_gte_0'), models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='product_selling_price_gte_0')],
            },
        ),
    ]
